{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux-test",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson-test",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux-test",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.5.jar",
          "url": "spring-boot-starter-webflux-test-4.0.5.jar",
          "size": 4763,
          "sha512": "0c09d64a7dba873090bf5733f37406e90a7e668d8acd17c234416f3899b3c065716a936f9943ea83d30ef56052ea0b3ce13ffdf45f6373d2119efb515a30a95a",
          "sha256": "2607b7cfb5254414565125c174af68a2d9c74bccc87eb228db78aeb7b3c90900",
          "sha1": "5f185eb8e6aeffb9f048627c36c4fea1dc38ad7d",
          "md5": "7f3c122e5df2b1fb72584464072d3a8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson-test",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux-test",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.5.jar",
          "url": "spring-boot-starter-webflux-test-4.0.5.jar",
          "size": 4763,
          "sha512": "0c09d64a7dba873090bf5733f37406e90a7e668d8acd17c234416f3899b3c065716a936f9943ea83d30ef56052ea0b3ce13ffdf45f6373d2119efb515a30a95a",
          "sha256": "2607b7cfb5254414565125c174af68a2d9c74bccc87eb228db78aeb7b3c90900",
          "sha1": "5f185eb8e6aeffb9f048627c36c4fea1dc38ad7d",
          "md5": "7f3c122e5df2b1fb72584464072d3a8f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-webflux-test-4.0.5-javadoc.jar",
          "size": 4763,
          "sha512": "0c09d64a7dba873090bf5733f37406e90a7e668d8acd17c234416f3899b3c065716a936f9943ea83d30ef56052ea0b3ce13ffdf45f6373d2119efb515a30a95a",
          "sha256": "2607b7cfb5254414565125c174af68a2d9c74bccc87eb228db78aeb7b3c90900",
          "sha1": "5f185eb8e6aeffb9f048627c36c4fea1dc38ad7d",
          "md5": "7f3c122e5df2b1fb72584464072d3a8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-test-4.0.5-sources.jar",
          "url": "spring-boot-starter-webflux-test-4.0.5-sources.jar",
          "size": 4763,
          "sha512": "0c09d64a7dba873090bf5733f37406e90a7e668d8acd17c234416f3899b3c065716a936f9943ea83d30ef56052ea0b3ce13ffdf45f6373d2119efb515a30a95a",
          "sha256": "2607b7cfb5254414565125c174af68a2d9c74bccc87eb228db78aeb7b3c90900",
          "sha1": "5f185eb8e6aeffb9f048627c36c4fea1dc38ad7d",
          "md5": "7f3c122e5df2b1fb72584464072d3a8f"
        }
      ]
    }
  ]
}
