{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-7.0.6.jar",
          "url": "spring-context-7.0.6.jar",
          "size": 1396752,
          "sha512": "9d696e49a06dcef893407bc7a97a079f385f368ee4beffbf5ec19ac5d3e9409e5b45205eb04b460b53d1310362b98fb8ce09b98486e31096e6fc256ba36cda8f",
          "sha256": "ba2920d69d96683425c0e6cc3717715d8ec1225988dcb1a6017815b70cf29d66",
          "sha1": "e722fa5455c1be437de1947d570506cb2bb142e9",
          "md5": "9ef8514ad19e44a0b414b91d465920df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-7.0.6.jar",
          "url": "spring-context-7.0.6.jar",
          "size": 1396752,
          "sha512": "9d696e49a06dcef893407bc7a97a079f385f368ee4beffbf5ec19ac5d3e9409e5b45205eb04b460b53d1310362b98fb8ce09b98486e31096e6fc256ba36cda8f",
          "sha256": "ba2920d69d96683425c0e6cc3717715d8ec1225988dcb1a6017815b70cf29d66",
          "sha1": "e722fa5455c1be437de1947d570506cb2bb142e9",
          "md5": "9ef8514ad19e44a0b414b91d465920df"
        }
      ]
    }
  ]
}
