{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-messaging",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-7.0.6.jar",
          "url": "spring-messaging-7.0.6.jar",
          "size": 613542,
          "sha512": "bb11a847fc73f9eaf58c0fc053fa352c351fc44ee52f0237cca1aaa5d12f65ca9b679b5cab93f6d4a067a6fc07dd9b652a7dac9f75957d3bae4a9a9e1839ef83",
          "sha256": "644e7c2468bfa3d9e79fb60c4d45596e3b211a58b1a3f20ffde0d20c70b94824",
          "sha1": "9b1fe6eb94f75b85ba75242a24c145be8ffc3beb",
          "md5": "84636276653e25b53db3ef3ea6ae1620"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-7.0.6.jar",
          "url": "spring-messaging-7.0.6.jar",
          "size": 613542,
          "sha512": "bb11a847fc73f9eaf58c0fc053fa352c351fc44ee52f0237cca1aaa5d12f65ca9b679b5cab93f6d4a067a6fc07dd9b652a7dac9f75957d3bae4a9a9e1839ef83",
          "sha256": "644e7c2468bfa3d9e79fb60c4d45596e3b211a58b1a3f20ffde0d20c70b94824",
          "sha1": "9b1fe6eb94f75b85ba75242a24c145be8ffc3beb",
          "md5": "84636276653e25b53db3ef3ea6ae1620"
        }
      ]
    }
  ]
}
