{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hamcrest",
    "module": "hamcrest",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hamcrest-3.0.jar",
          "url": "hamcrest-3.0.jar",
          "size": 126373,
          "sha512": "c09968882d8467d43576444b3fab868e175f0826e1d6e2015d1efec8934cdd5ffce8f285a7fc072306711ee0645dea92783a97a9e1dd8206e5e1de5de1ea8e7f",
          "sha256": "5d66b6a4a680755cb6ed7cb104fa7835ef644667586ff0737adeb977c39ecdbc",
          "sha1": "8fd9b78a8e6a6510a078a9e30e9e86a6035cfaf7",
          "md5": "781023c38b054e9cf1c818c77895e1eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hamcrest-3.0.jar",
          "url": "hamcrest-3.0.jar",
          "size": 126373,
          "sha512": "c09968882d8467d43576444b3fab868e175f0826e1d6e2015d1efec8934cdd5ffce8f285a7fc072306711ee0645dea92783a97a9e1dd8206e5e1de5de1ea8e7f",
          "sha256": "5d66b6a4a680755cb6ed7cb104fa7835ef644667586ff0737adeb977c39ecdbc",
          "sha1": "8fd9b78a8e6a6510a078a9e30e9e86a6035cfaf7",
          "md5": "781023c38b054e9cf1c818c77895e1eb"
        }
      ]
    }
  ]
}
