{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jackson",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.5.jar",
          "url": "spring-boot-starter-jackson-4.0.5.jar",
          "size": 4741,
          "sha512": "a54ddfb6b7c965a16e226fa379b49d7ff9dde8f1f49f54cc2545b5f4edcb67656445299ec0678a60480e111a5bb60137df5e93bd590e57ec7c1cf8628f1bbdc1",
          "sha256": "2952761d6d312eecd20d19990f7eaae6e610d7743d40537eecead65a685a46d0",
          "sha1": "16d3f8e99476fd61f39de7e96d2b66a2d18e943d",
          "md5": "fd9e14f9efdfa2e312c6f990501c3ba6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jackson",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.5.jar",
          "url": "spring-boot-starter-jackson-4.0.5.jar",
          "size": 4741,
          "sha512": "a54ddfb6b7c965a16e226fa379b49d7ff9dde8f1f49f54cc2545b5f4edcb67656445299ec0678a60480e111a5bb60137df5e93bd590e57ec7c1cf8628f1bbdc1",
          "sha256": "2952761d6d312eecd20d19990f7eaae6e610d7743d40537eecead65a685a46d0",
          "sha1": "16d3f8e99476fd61f39de7e96d2b66a2d18e943d",
          "md5": "fd9e14f9efdfa2e312c6f990501c3ba6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-jackson-4.0.5-javadoc.jar",
          "size": 4741,
          "sha512": "a54ddfb6b7c965a16e226fa379b49d7ff9dde8f1f49f54cc2545b5f4edcb67656445299ec0678a60480e111a5bb60137df5e93bd590e57ec7c1cf8628f1bbdc1",
          "sha256": "2952761d6d312eecd20d19990f7eaae6e610d7743d40537eecead65a685a46d0",
          "sha1": "16d3f8e99476fd61f39de7e96d2b66a2d18e943d",
          "md5": "fd9e14f9efdfa2e312c6f990501c3ba6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jackson-4.0.5-sources.jar",
          "url": "spring-boot-starter-jackson-4.0.5-sources.jar",
          "size": 4741,
          "sha512": "a54ddfb6b7c965a16e226fa379b49d7ff9dde8f1f49f54cc2545b5f4edcb67656445299ec0678a60480e111a5bb60137df5e93bd590e57ec7c1cf8628f1bbdc1",
          "sha256": "2952761d6d312eecd20d19990f7eaae6e610d7743d40537eecead65a685a46d0",
          "sha1": "16d3f8e99476fd61f39de7e96d2b66a2d18e943d",
          "md5": "fd9e14f9efdfa2e312c6f990501c3ba6"
        }
      ]
    }
  ]
}
