{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-mongodb",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-mongodb",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mongodb-4.0.5.jar",
          "url": "spring-boot-starter-mongodb-4.0.5.jar",
          "size": 4764,
          "sha512": "5de0ae9884caee4df3c0a4a0f4f1c0ceb75611dbe44603b5a47a0b3e5c93acf84265f8bde867bbb850d485bf2d5e35576594f5fcd5be92303076e1a9dcfcbfb5",
          "sha256": "6d092020660305ef9ba4f323d5d2159f0f802cabe92d58c1266862d1796f1176",
          "sha1": "31e6bb5af7959868d207acd82ed01f4a45fbf60d",
          "md5": "b0f0da68d706fe1fda30daec433f5031"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-mongodb",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mongodb-4.0.5.jar",
          "url": "spring-boot-starter-mongodb-4.0.5.jar",
          "size": 4764,
          "sha512": "5de0ae9884caee4df3c0a4a0f4f1c0ceb75611dbe44603b5a47a0b3e5c93acf84265f8bde867bbb850d485bf2d5e35576594f5fcd5be92303076e1a9dcfcbfb5",
          "sha256": "6d092020660305ef9ba4f323d5d2159f0f802cabe92d58c1266862d1796f1176",
          "sha1": "31e6bb5af7959868d207acd82ed01f4a45fbf60d",
          "md5": "b0f0da68d706fe1fda30daec433f5031"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mongodb-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-mongodb-4.0.5-javadoc.jar",
          "size": 4764,
          "sha512": "5de0ae9884caee4df3c0a4a0f4f1c0ceb75611dbe44603b5a47a0b3e5c93acf84265f8bde867bbb850d485bf2d5e35576594f5fcd5be92303076e1a9dcfcbfb5",
          "sha256": "6d092020660305ef9ba4f323d5d2159f0f802cabe92d58c1266862d1796f1176",
          "sha1": "31e6bb5af7959868d207acd82ed01f4a45fbf60d",
          "md5": "b0f0da68d706fe1fda30daec433f5031"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mongodb-4.0.5-sources.jar",
          "url": "spring-boot-starter-mongodb-4.0.5-sources.jar",
          "size": 4764,
          "sha512": "5de0ae9884caee4df3c0a4a0f4f1c0ceb75611dbe44603b5a47a0b3e5c93acf84265f8bde867bbb850d485bf2d5e35576594f5fcd5be92303076e1a9dcfcbfb5",
          "sha256": "6d092020660305ef9ba4f323d5d2159f0f802cabe92d58c1266862d1796f1176",
          "sha1": "31e6bb5af7959868d207acd82ed01f4a45fbf60d",
          "md5": "b0f0da68d706fe1fda30daec433f5031"
        }
      ]
    }
  ]
}
