{
  "formatVersion": "1.1",
  "component": {
    "group": "co.elastic.clients",
    "module": "elasticsearch-java",
    "version": "9.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.2.6"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "jakarta.json",
          "module": "jakarta.json-api",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.eclipse.parsson",
          "module": "parsson",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "elasticsearch-java-9.2.6.jar",
          "url": "elasticsearch-java-9.2.6.jar",
          "size": 13400341,
          "sha512": "0a1d90a474c9c9c5d1f46924dd4e2133026d5e7ebd0abd1b16b1da0d6560710d1672058f377d85a898cded47b3090c65d0cc527592cb6628cc0720ce9d9c27cb",
          "sha256": "be0119aa30212ac388ed8fdb1eba06a115f8ddf4e565464a30db7a243eaa1293",
          "sha1": "38ba8bd8e06283ab13d042b8b04222fa5fa44685",
          "md5": "98639db34b16d2242dd49fad9deb2da3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.37.0"
          }
        },
        {
          "group": "io.opentelemetry.semconv",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.37.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.2.6"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "jakarta.json",
          "module": "jakarta.json-api",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.eclipse.parsson",
          "module": "parsson",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "elasticsearch-java-9.2.6.jar",
          "url": "elasticsearch-java-9.2.6.jar",
          "size": 13400341,
          "sha512": "0a1d90a474c9c9c5d1f46924dd4e2133026d5e7ebd0abd1b16b1da0d6560710d1672058f377d85a898cded47b3090c65d0cc527592cb6628cc0720ce9d9c27cb",
          "sha256": "be0119aa30212ac388ed8fdb1eba06a115f8ddf4e565464a30db7a243eaa1293",
          "sha1": "38ba8bd8e06283ab13d042b8b04222fa5fa44685",
          "md5": "98639db34b16d2242dd49fad9deb2da3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elasticsearch-java-9.2.6-javadoc.jar",
          "url": "elasticsearch-java-9.2.6-javadoc.jar",
          "size": 31288414,
          "sha512": "a7dc238542cdc3138794fdba69d1fa03e6c9ba8154da63033bc3fa24fa7283152b6c7900a53c0150499c97c7ffa43f07aa985dfdcc03843f5e5ee1f5805e0cf6",
          "sha256": "7edbbc89cc5a7c27ec82aa3b628cca30db73b74e8eb8c55b934ae21ceb0a46c0",
          "sha1": "715d11538cd7b2ae4d3a1be1dabde1ef33f4f0bf",
          "md5": "1071350a4ee235c0982997148991842a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elasticsearch-java-9.2.6-sources.jar",
          "url": "elasticsearch-java-9.2.6-sources.jar",
          "size": 9058309,
          "sha512": "beaded77c281e688cf6771330bcda8aea705b0d2ced6da54ebde5a335bfb4396b4a4d6495a20a1ab5f05d770035d427b4ee4b273087d834bff014cfa2b3e392a",
          "sha256": "76687c75d9a06e52b463a609e8dca23ac6c1eef26edf86a1d070a646c8f2fe0a",
          "sha1": "7810fd04525a0257fe23006f4eaaeafce780092a",
          "md5": "dcae8bbe342f2aabfdf2c707e1c86e9c"
        }
      ]
    }
  ]
}
