spring.application.name=Quora
spring.data.mongodb.uri=mongodb://localhost:27017/quoraDb
spring.data.mongodb.auto-index-creation=true
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.repositories.enabled=false