{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-reactor-netty",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor-netty",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.5.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.5.jar",
          "size": 4743,
          "sha512": "827203d3343ad280c95068433ac40430bd1aedd09f822b7430a2ea94b5b6af5a9bcacc21de6a498bf3e8b21d81d39959e6f431807df97722d9dbe7c6ff946359",
          "sha256": "a1d8d8d01dce38913523fc80fe5eb1f7b8b84b9b5e27f20e79ac4d12804b9fe9",
          "sha1": "5e64ab82ccee48327a51152a7de98848bee51fb4",
          "md5": "d014fb88366a6c56729008b1f50697f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor-netty",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.5.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.5.jar",
          "size": 4743,
          "sha512": "827203d3343ad280c95068433ac40430bd1aedd09f822b7430a2ea94b5b6af5a9bcacc21de6a498bf3e8b21d81d39959e6f431807df97722d9dbe7c6ff946359",
          "sha256": "a1d8d8d01dce38913523fc80fe5eb1f7b8b84b9b5e27f20e79ac4d12804b9fe9",
          "sha1": "5e64ab82ccee48327a51152a7de98848bee51fb4",
          "md5": "d014fb88366a6c56729008b1f50697f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.5-javadoc.jar",
          "size": 4743,
          "sha512": "827203d3343ad280c95068433ac40430bd1aedd09f822b7430a2ea94b5b6af5a9bcacc21de6a498bf3e8b21d81d39959e6f431807df97722d9dbe7c6ff946359",
          "sha256": "a1d8d8d01dce38913523fc80fe5eb1f7b8b84b9b5e27f20e79ac4d12804b9fe9",
          "sha1": "5e64ab82ccee48327a51152a7de98848bee51fb4",
          "md5": "d014fb88366a6c56729008b1f50697f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-4.0.5-sources.jar",
          "url": "spring-boot-starter-reactor-netty-4.0.5-sources.jar",
          "size": 4743,
          "sha512": "827203d3343ad280c95068433ac40430bd1aedd09f822b7430a2ea94b5b6af5a9bcacc21de6a498bf3e8b21d81d39959e6f431807df97722d9dbe7c6ff946359",
          "sha256": "a1d8d8d01dce38913523fc80fe5eb1f7b8b84b9b5e27f20e79ac4d12804b9fe9",
          "sha1": "5e64ab82ccee48327a51152a7de98848bee51fb4",
          "md5": "d014fb88366a6c56729008b1f50697f9"
        }
      ]
    }
  ]
}
