{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-web-server",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.5.jar",
          "url": "spring-boot-web-server-4.0.5.jar",
          "size": 169265,
          "sha512": "b6d33e0580dcaa63f55fda051fc167cfdd56c70a56788b12d0788c3eacbf36645d07dbc85d66846a019384a5dea2915a6685c4d77d0fd9d11e5835c5e4189e22",
          "sha256": "221346176ddd88d6c0773bdb3d37948ad9bc883265862c7c9365dd9a163dac2f",
          "sha1": "e70e3422c68f2fae6fcb2782be5fa31c0a788a6d",
          "md5": "dc0e45385058ea976a805a66400ca4e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.5.jar",
          "url": "spring-boot-web-server-4.0.5.jar",
          "size": 169265,
          "sha512": "b6d33e0580dcaa63f55fda051fc167cfdd56c70a56788b12d0788c3eacbf36645d07dbc85d66846a019384a5dea2915a6685c4d77d0fd9d11e5835c5e4189e22",
          "sha256": "221346176ddd88d6c0773bdb3d37948ad9bc883265862c7c9365dd9a163dac2f",
          "sha1": "e70e3422c68f2fae6fcb2782be5fa31c0a788a6d",
          "md5": "dc0e45385058ea976a805a66400ca4e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.5-javadoc.jar",
          "url": "spring-boot-web-server-4.0.5-javadoc.jar",
          "size": 411069,
          "sha512": "28b53d8be089a62eb94c5fe3664853f133eaf5838d3718e5044b43cb904dcd26b4142c1bc2e8822349fc9995f884a4f365d8fe6a9f1165ed3df8e1382b708e55",
          "sha256": "e520cbd71b77832334e967ecadfc20d7628d942de37e6a283332cae69a1bf92b",
          "sha1": "014d74579009800555eba1458ddadc1a71b7aec2",
          "md5": "b3ae153e9692997532fd30bd249c48f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.5-sources.jar",
          "url": "spring-boot-web-server-4.0.5-sources.jar",
          "size": 129322,
          "sha512": "f8a24563f97046aa687f963315ef36178378a0a7236df49ee76075a20d9530c2d89de56cde862b274f0d0acb0630a6f4a60835edf9c66748da6f33460bd76837",
          "sha256": "c45c0d548dc092a591a57ade7cd4d89f893c757b28262658ff4b27281cd82b44",
          "sha1": "c66b80e100c5586c64e2d3c421418e55a82785e6",
          "md5": "7583f123e2b07c3ca1c39d6d5520c3cb"
        }
      ]
    }
  ]
}
