{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-webflux-test",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.5.jar",
          "url": "spring-boot-webflux-test-4.0.5.jar",
          "size": 10833,
          "sha512": "1e90473aa52d30012b8950c980a28afe6568d3a39b926fb90a6f076f401fdd7318f49955f289d8f6422d1db11a680cc1b353f7eb488f848dcc6c916f47cf98c2",
          "sha256": "0b72d1e6062ffab216b631c0aa52b4820deef6ebd2e7d4ad94b22228cedc4d82",
          "sha1": "6952ff46b12619816373ecb64d5cafb159b3b018",
          "md5": "3472694977ef8f00b9bfba1544e893cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webtestclient",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.5.jar",
          "url": "spring-boot-webflux-test-4.0.5.jar",
          "size": 10833,
          "sha512": "1e90473aa52d30012b8950c980a28afe6568d3a39b926fb90a6f076f401fdd7318f49955f289d8f6422d1db11a680cc1b353f7eb488f848dcc6c916f47cf98c2",
          "sha256": "0b72d1e6062ffab216b631c0aa52b4820deef6ebd2e7d4ad94b22228cedc4d82",
          "sha1": "6952ff46b12619816373ecb64d5cafb159b3b018",
          "md5": "3472694977ef8f00b9bfba1544e893cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.5-javadoc.jar",
          "url": "spring-boot-webflux-test-4.0.5-javadoc.jar",
          "size": 110622,
          "sha512": "8364aa777e297c9ffc4f35d4a0f44d86f61668bdd40b9db3567da2d8d77bb79f1969cf41ca10627020b2c50a3000707cea8d7a1292fe62f7a7ba67e4ee1d839d",
          "sha256": "6e9968967b2ac8bc7bba212c2d2401c04a490b2748c1ba50826ef34a78acbf24",
          "sha1": "df3fba215169c2089720ade758605db28a7d1d7f",
          "md5": "32b234c5083752d5e3a048968a2e4166"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-webflux-test-4.0.5-sources.jar",
          "url": "spring-boot-webflux-test-4.0.5-sources.jar",
          "size": 12551,
          "sha512": "c0c650eeaddf65ec41b45f9f24969f8152499fab8f887202162a95df6db6f721881bab60dba09a62152572687b3362145c73cc6ef3730729376301b9423ae135",
          "sha256": "16d43bff6073c18d4a9c22380f6c414bef14bf370f06374522e6b80c10575c88",
          "sha1": "2705cb4100276db822f1a4712ba5bd01178fda2a",
          "md5": "4cda4e0021f42d2d64a6bda39796fc04"
        }
      ]
    }
  ]
}
