{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.kafka",
    "module": "spring-kafka",
    "version": "3.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.1.2.jar",
          "url": "spring-kafka-3.1.2.jar",
          "size": 822304,
          "sha512": "ffa9e8b23646714745b42941fa914dfa6e1627a8dbb77726a4adeb4921a864927d42a500fb0af38cf5c7ebfe28f1acfb4d5bf26570285b2dbe385de1169f53d7",
          "sha256": "1e96e8ebffb46b0ee050996f9396633421a8d94e219f1c906f68caef09f98cda",
          "sha1": "a7a304f5debd5673d4176c760efe4e248b4e548d",
          "md5": "ab3454ec55a93530281b7b4fe2aa9c8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.1.2.jar",
          "url": "spring-kafka-3.1.2.jar",
          "size": 822304,
          "sha512": "ffa9e8b23646714745b42941fa914dfa6e1627a8dbb77726a4adeb4921a864927d42a500fb0af38cf5c7ebfe28f1acfb4d5bf26570285b2dbe385de1169f53d7",
          "sha256": "1e96e8ebffb46b0ee050996f9396633421a8d94e219f1c906f68caef09f98cda",
          "sha1": "a7a304f5debd5673d4176c760efe4e248b4e548d",
          "md5": "ab3454ec55a93530281b7b4fe2aa9c8d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-3.1.2-javadoc.jar",
          "url": "spring-kafka-3.1.2-javadoc.jar",
          "size": 1573546,
          "sha512": "033ae5a748821a4a18c6abe9f57033cc8f6e254766cf3d6aca4cbf658ec21ea681c5e98ca6e3dae895d9b5d8a3a3fe40a3284048b4d18f14996a574e9ed53521",
          "sha256": "acd4362850dfda7c5dec5cfa57c6ab911fb359f77fca21df97fe705bf109cbff",
          "sha1": "d228a0b190a97c8d0b9329e0464518164efc8355",
          "md5": "7e74ab56305850f01e488c3797758a66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-3.1.2-sources.jar",
          "url": "spring-kafka-3.1.2-sources.jar",
          "size": 554332,
          "sha512": "691d6b283232f9482d27e02b53f758ef0b16e2e59456418411bac63d314cbf038e44a9d5a847ab65c3c37e5ca48cbe2ae714f0dec197014e6afdaa9d6e337e35",
          "sha256": "d8e7d912c6eeba14050dcb66d62c930a680c6e3119a796629fa693866b47b9fb",
          "sha1": "44c18dd9a877594487ef37d32befeb2c3ebdf6bb",
          "md5": "7df9cca2796c4f88970cdec48662e421"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.15.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.2.3"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.23"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.12.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.1.2.jar",
          "url": "spring-kafka-3.1.2.jar",
          "size": 822304,
          "sha512": "ffa9e8b23646714745b42941fa914dfa6e1627a8dbb77726a4adeb4921a864927d42a500fb0af38cf5c7ebfe28f1acfb4d5bf26570285b2dbe385de1169f53d7",
          "sha256": "1e96e8ebffb46b0ee050996f9396633421a8d94e219f1c906f68caef09f98cda",
          "sha1": "a7a304f5debd5673d4176c760efe4e248b4e548d",
          "md5": "ab3454ec55a93530281b7b4fe2aa9c8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "3.1.2"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.15.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.15.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.2.3"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.23"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.12.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.1.2.jar",
          "url": "spring-kafka-3.1.2.jar",
          "size": 822304,
          "sha512": "ffa9e8b23646714745b42941fa914dfa6e1627a8dbb77726a4adeb4921a864927d42a500fb0af38cf5c7ebfe28f1acfb4d5bf26570285b2dbe385de1169f53d7",
          "sha256": "1e96e8ebffb46b0ee050996f9396633421a8d94e219f1c906f68caef09f98cda",
          "sha1": "a7a304f5debd5673d4176c760efe4e248b4e548d",
          "md5": "ab3454ec55a93530281b7b4fe2aa9c8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "3.1.2"
        }
      ]
    }
  ]
}
