{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-reactor-netty",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.5.jar",
          "url": "spring-boot-reactor-netty-4.0.5.jar",
          "size": 41836,
          "sha512": "ad59ff6ca308e69fbe42df6d2c7fcd833de068708c75167f78ebc2a81c692be9ed2a335af73314baaafa8ecaeb9ec8f980fbcfea3dce6a631de287cc8563989d",
          "sha256": "ee8223b9de29c7be73147f12b1a0e7ee9a99defdb9b23499a450c7db789ed351",
          "sha1": "91cfce8fac2858fe0c519479b302509790fbc25a",
          "md5": "19aa62b0adb49a043dab48d234478dc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-netty",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.5.jar",
          "url": "spring-boot-reactor-netty-4.0.5.jar",
          "size": 41836,
          "sha512": "ad59ff6ca308e69fbe42df6d2c7fcd833de068708c75167f78ebc2a81c692be9ed2a335af73314baaafa8ecaeb9ec8f980fbcfea3dce6a631de287cc8563989d",
          "sha256": "ee8223b9de29c7be73147f12b1a0e7ee9a99defdb9b23499a450c7db789ed351",
          "sha1": "91cfce8fac2858fe0c519479b302509790fbc25a",
          "md5": "19aa62b0adb49a043dab48d234478dc2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.5-javadoc.jar",
          "url": "spring-boot-reactor-netty-4.0.5-javadoc.jar",
          "size": 152809,
          "sha512": "4aca57a91cb89d21e003f9956cc6c283221412b091eabe4f1ebaad4ec5f7fe5a2d6bb1ede65da9b2c245a3f727e32825f9ac0d99447f915849f161cab19e18bc",
          "sha256": "87726e47ecf4cc875b1c7e1296bacbfc984fd14288006e9e8cb7bd0ef3041243",
          "sha1": "e96656368b8e2ae53cd11e1147f755027a30e67d",
          "md5": "75e4ee4d293cea5caec39aa3fb52dd06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-reactor-netty-4.0.5-sources.jar",
          "url": "spring-boot-reactor-netty-4.0.5-sources.jar",
          "size": 30288,
          "sha512": "7655a25156691eef04982e82ff85c0d5f0b3dd5952e971566938f10c05b61b1bfe236624e82772151c8339e410ae9016b79a17954551a04b32c6ea6995aa60ce",
          "sha256": "76a2aac1143ddfa8ee5c49e0665976badd2f141c2163e79ffc647c606a8858fe",
          "sha1": "2efe8d8e43bc6447a32fd6e046b3de2347390ee6",
          "md5": "66cf3e2c06088555d92af79ea9542095"
        }
      ]
    }
  ]
}
