{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.5.jar",
          "url": "spring-boot-starter-webflux-4.0.5.jar",
          "size": 4756,
          "sha512": "7e3f1d565d53bca20085dd56cfa9cb9a4d2616f29a22634f49f4bdb2aef696cea5c7e2f83f8e77b6a5729054af24d26b009c1c3ffdc4372f7607c53e7f4e30fe",
          "sha256": "c13b24083140b8ff297bb1fb5a53cfad20ed63acc16f5cf41df1a8fedc889193",
          "sha1": "19b3c34e68056be0e3ad3d98846e6026281e113b",
          "md5": "69fe2fecd50a0ae3a8a5555c88b8f954"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-reactor",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webflux",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.5.jar",
          "url": "spring-boot-starter-webflux-4.0.5.jar",
          "size": 4756,
          "sha512": "7e3f1d565d53bca20085dd56cfa9cb9a4d2616f29a22634f49f4bdb2aef696cea5c7e2f83f8e77b6a5729054af24d26b009c1c3ffdc4372f7607c53e7f4e30fe",
          "sha256": "c13b24083140b8ff297bb1fb5a53cfad20ed63acc16f5cf41df1a8fedc889193",
          "sha1": "19b3c34e68056be0e3ad3d98846e6026281e113b",
          "md5": "69fe2fecd50a0ae3a8a5555c88b8f954"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-webflux-4.0.5-javadoc.jar",
          "size": 4756,
          "sha512": "7e3f1d565d53bca20085dd56cfa9cb9a4d2616f29a22634f49f4bdb2aef696cea5c7e2f83f8e77b6a5729054af24d26b009c1c3ffdc4372f7607c53e7f4e30fe",
          "sha256": "c13b24083140b8ff297bb1fb5a53cfad20ed63acc16f5cf41df1a8fedc889193",
          "sha1": "19b3c34e68056be0e3ad3d98846e6026281e113b",
          "md5": "69fe2fecd50a0ae3a8a5555c88b8f954"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-4.0.5-sources.jar",
          "url": "spring-boot-starter-webflux-4.0.5-sources.jar",
          "size": 4756,
          "sha512": "7e3f1d565d53bca20085dd56cfa9cb9a4d2616f29a22634f49f4bdb2aef696cea5c7e2f83f8e77b6a5729054af24d26b009c1c3ffdc4372f7607c53e7f4e30fe",
          "sha256": "c13b24083140b8ff297bb1fb5a53cfad20ed63acc16f5cf41df1a8fedc889193",
          "sha1": "19b3c34e68056be0e3ad3d98846e6026281e113b",
          "md5": "69fe2fecd50a0ae3a8a5555c88b8f954"
        }
      ]
    }
  ]
}
