{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-netty",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-netty-4.0.5.jar",
          "url": "spring-boot-netty-4.0.5.jar",
          "size": 9809,
          "sha512": "bda9bf79973678d4efb48a4d524397e1f7d35a37a9e6d01b848aba6286eaa1a57e3066c5935342d67225eec8ea8db441f40854af1ca34749ec6142696f8bed6f",
          "sha256": "2cde54927a20ff1e967beeb34d1e34a07e58ba4412f0864fc347560eb8afa150",
          "sha1": "d1704c93f3196c14e86f17168f8363037553627e",
          "md5": "aa636b1e29545ba4a8ee4c5cd837fd16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.2.12.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-netty-4.0.5.jar",
          "url": "spring-boot-netty-4.0.5.jar",
          "size": 9809,
          "sha512": "bda9bf79973678d4efb48a4d524397e1f7d35a37a9e6d01b848aba6286eaa1a57e3066c5935342d67225eec8ea8db441f40854af1ca34749ec6142696f8bed6f",
          "sha256": "2cde54927a20ff1e967beeb34d1e34a07e58ba4412f0864fc347560eb8afa150",
          "sha1": "d1704c93f3196c14e86f17168f8363037553627e",
          "md5": "aa636b1e29545ba4a8ee4c5cd837fd16"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-netty-4.0.5-javadoc.jar",
          "url": "spring-boot-netty-4.0.5-javadoc.jar",
          "size": 113853,
          "sha512": "549c704114a01e3652f56dcca01f7a83ffe6239248b2883ab4796d72ffbfa56c64d5bd59ee8665de925ee08b384e5bf69a1b2da468f2bbaf62d1dad833fd4a0e",
          "sha256": "b086921e8470f6af030f5fe637047bd0d507b174c6d72ed0ad1022d9ada6c476",
          "sha1": "3f5fde48df4fd4bb6d691d21d5eb0c8adedf2497",
          "md5": "872c8771f4fd9926e91c35bf2bbef848"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-netty-4.0.5-sources.jar",
          "url": "spring-boot-netty-4.0.5-sources.jar",
          "size": 8729,
          "sha512": "99e388bc0d153545f80a51686fae56a8fc4f0fad66eb0f1bf736ab90e8fc5a1ef63e5a33e4333949ad1c5a5ae65b3bb8c21723ba234b4dc785362256153b3556",
          "sha256": "11b4752ffc3e7e31e668221102d788d923d76e8e2c4036647552b72795e890a7",
          "sha1": "d9b1fa1cc01cee4e2f8aa145155f7769a46dddad",
          "md5": "76ab0598f79e479c5ee23837b52adbcd"
        }
      ]
    }
  ]
}
