{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-bom",
    "version": "7.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-access",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-acl",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-aspects",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-cas",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-data",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-client",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-test",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-web",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-ldap",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-messaging",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-authorization-server",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-resource-server",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-rsocket",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-saml2-service-provider",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-taglibs",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-test",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-webauthn",
          "version": {
            "requires": "7.0.4"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-access",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-acl",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-aspects",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-cas",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-data",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-client",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-test",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-kerberos-web",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-ldap",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-messaging",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-authorization-server",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-resource-server",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-rsocket",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-saml2-service-provider",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-taglibs",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-test",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-webauthn",
          "version": {
            "requires": "7.0.4"
          }
        }
      ]
    }
  ]
}
