{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.kafka",
    "module": "spring-kafka",
    "version": "4.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-4.0.4.jar",
          "url": "spring-kafka-4.0.4.jar",
          "size": 968234,
          "sha512": "05e964659e45ebf22ebabac7fefeb19787142c1082d4ea324f6c73d6c8f53da2c17a8c69f777f943de8587866bd5527457c807b55a6dad3c74815a6c22eaf97a",
          "sha256": "1948c044e2a58420069783f556f822ae3d42412c697e85f3bde335772aacfd1b",
          "sha1": "92ad03c6839539b25d485fe25d5be66b34a95071",
          "md5": "aa471e140f6a1d47466d792ba63eaf37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-4.0.4.jar",
          "url": "spring-kafka-4.0.4.jar",
          "size": 968234,
          "sha512": "05e964659e45ebf22ebabac7fefeb19787142c1082d4ea324f6c73d6c8f53da2c17a8c69f777f943de8587866bd5527457c807b55a6dad3c74815a6c22eaf97a",
          "sha256": "1948c044e2a58420069783f556f822ae3d42412c697e85f3bde335772aacfd1b",
          "sha1": "92ad03c6839539b25d485fe25d5be66b34a95071",
          "md5": "aa471e140f6a1d47466d792ba63eaf37"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-4.0.4-javadoc.jar",
          "url": "spring-kafka-4.0.4-javadoc.jar",
          "size": 5951734,
          "sha512": "739b186edc5908305d660c3cdee315065d47ebb5fc88f2d8336155ee05b4332308428d336e53f837c2ba98ddff0d2bca5c3308d37c8aa265df2f4b7f769469bb",
          "sha256": "e2e24c9dd759fde15f282bb152bef10a888c32d3683cf288b8ed7867e07b67c6",
          "sha1": "6207f539c30d7438d338ef9019cf308671af7cf5",
          "md5": "338277898781f46685b90227be11fb35"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-4.0.4-sources.jar",
          "url": "spring-kafka-4.0.4-sources.jar",
          "size": 651224,
          "sha512": "fffe27f617fbcbe401d48c420108287d5286397ec599fb114442d63e911385a271f4a6e6de3360b8ca19b80da94fef8683f4820d1cb757d104cdf8fa7ad659a8",
          "sha256": "aedc76cbc8675d05cc4259ac54244f706fe0a4d5035f4a8e4a7d02dfd12804ba",
          "sha1": "cba41ae9376646f195b93f3e0567ec29f93e8fd6",
          "md5": "6c83cba7b7b976c6ed28fb34a040b944"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.20.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "tools.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "4.0.4"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-4.0.4.jar",
          "url": "spring-kafka-4.0.4.jar",
          "size": 968234,
          "sha512": "05e964659e45ebf22ebabac7fefeb19787142c1082d4ea324f6c73d6c8f53da2c17a8c69f777f943de8587866bd5527457c807b55a6dad3c74815a6c22eaf97a",
          "sha256": "1948c044e2a58420069783f556f822ae3d42412c697e85f3bde335772aacfd1b",
          "sha1": "92ad03c6839539b25d485fe25d5be66b34a95071",
          "md5": "aa471e140f6a1d47466d792ba63eaf37"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "4.0.4"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.20.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.20.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "tools.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "4.0.4"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-4.0.4.jar",
          "url": "spring-kafka-4.0.4.jar",
          "size": 968234,
          "sha512": "05e964659e45ebf22ebabac7fefeb19787142c1082d4ea324f6c73d6c8f53da2c17a8c69f777f943de8587866bd5527457c807b55a6dad3c74815a6c22eaf97a",
          "sha256": "1948c044e2a58420069783f556f822ae3d42412c697e85f3bde335772aacfd1b",
          "sha1": "92ad03c6839539b25d485fe25d5be66b34a95071",
          "md5": "aa471e140f6a1d47466d792ba63eaf37"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "4.0.4"
        }
      ]
    }
  ]
}
