{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.platform",
    "module": "junit-platform-engine",
    "version": "6.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "6.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-engine-6.0.3.jar",
          "url": "junit-platform-engine-6.0.3.jar",
          "size": 280233,
          "sha512": "0235da442ee6e189a87f06415c97fdbae1146f5a18ba2e0e9fc57a86916fe4ca1ccf883bb8b96730a524179217de88638cdf87ce7c8ba284cd0fe6f79d93f7aa",
          "sha256": "491e9e4f745f161b8a8e4186a1a7c6a450ea12c70930c9aedae427215301d947",
          "sha1": "101305612e7daa4ce978d3ba73fd02dd4a5f22d9",
          "md5": "ca09bac92bc2e093a81459cf04fb02a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "6.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "6.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-engine-6.0.3.jar",
          "url": "junit-platform-engine-6.0.3.jar",
          "size": 280233,
          "sha512": "0235da442ee6e189a87f06415c97fdbae1146f5a18ba2e0e9fc57a86916fe4ca1ccf883bb8b96730a524179217de88638cdf87ce7c8ba284cd0fe6f79d93f7aa",
          "sha256": "491e9e4f745f161b8a8e4186a1a7c6a450ea12c70930c9aedae427215301d947",
          "sha1": "101305612e7daa4ce978d3ba73fd02dd4a5f22d9",
          "md5": "ca09bac92bc2e093a81459cf04fb02a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-engine-6.0.3-javadoc.jar",
          "url": "junit-platform-engine-6.0.3-javadoc.jar",
          "size": 4912015,
          "sha512": "478d4bcc9060546a04f71faacf0d57d2f2d4672cc0cc1c5f0329dbf312597f19e55b167325e2c1841d7b9b7f4330eb11eb959dc289fa86d8fd3539cd27e3c026",
          "sha256": "05732d19ee2dbdb31db005468e22a69d4ecad7ad6c465311e928b35c8c3bc204",
          "sha1": "214bc76db92d938c996c009ce2f173026b11eaf5",
          "md5": "5bb1ee660cc86bf80a3901e571b9d46f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-engine-6.0.3-sources.jar",
          "url": "junit-platform-engine-6.0.3-sources.jar",
          "size": 174840,
          "sha512": "05b74f0fe6d8ac5d8bdbeb8f9782d6a4d29b05ebf5431d1a251bf05f6931dbfdd8dd4bb0eda3053333b77af1aba551bb2cc1a36d752eddb4437c800d276dd958",
          "sha256": "89a893566a97557dbbcb0706d9b5565c4e7a402050841753dc527f3e9139c9ac",
          "sha1": "15cd543d3a2c2a9165ef6108b1bd7d31ec6e9356",
          "md5": "036ff9e980610e29262d39d6b7274972"
        }
      ]
    }
  ]
}
