{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.5.jar",
          "url": "spring-boot-starter-4.0.5.jar",
          "size": 4768,
          "sha512": "cb613bf9c4e349dc0b5c19e9504830dc36bd83249c5dacc23a143e9d9782c221c3faccd009ff7574d1527f6676e0c3f1e318b1fe4ffe42910f6b96a9bbf6b83a",
          "sha256": "a66af4dc267e77df48f911ece01dc825b6c9075a66d1994b067d83e44e2f2a81",
          "sha1": "2767611655cf4a17306c3331f95b6f90db83ee06",
          "md5": "29ee89461a22c381ac2b748c2f266d17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.5.jar",
          "url": "spring-boot-starter-4.0.5.jar",
          "size": 4768,
          "sha512": "cb613bf9c4e349dc0b5c19e9504830dc36bd83249c5dacc23a143e9d9782c221c3faccd009ff7574d1527f6676e0c3f1e318b1fe4ffe42910f6b96a9bbf6b83a",
          "sha256": "a66af4dc267e77df48f911ece01dc825b6c9075a66d1994b067d83e44e2f2a81",
          "sha1": "2767611655cf4a17306c3331f95b6f90db83ee06",
          "md5": "29ee89461a22c381ac2b748c2f266d17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.5-javadoc.jar",
          "url": "spring-boot-starter-4.0.5-javadoc.jar",
          "size": 4768,
          "sha512": "cb613bf9c4e349dc0b5c19e9504830dc36bd83249c5dacc23a143e9d9782c221c3faccd009ff7574d1527f6676e0c3f1e318b1fe4ffe42910f6b96a9bbf6b83a",
          "sha256": "a66af4dc267e77df48f911ece01dc825b6c9075a66d1994b067d83e44e2f2a81",
          "sha1": "2767611655cf4a17306c3331f95b6f90db83ee06",
          "md5": "29ee89461a22c381ac2b748c2f266d17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.5-sources.jar",
          "url": "spring-boot-starter-4.0.5-sources.jar",
          "size": 4768,
          "sha512": "cb613bf9c4e349dc0b5c19e9504830dc36bd83249c5dacc23a143e9d9782c221c3faccd009ff7574d1527f6676e0c3f1e318b1fe4ffe42910f6b96a9bbf6b83a",
          "sha256": "a66af4dc267e77df48f911ece01dc825b6c9075a66d1994b067d83e44e2f2a81",
          "sha1": "2767611655cf4a17306c3331f95b6f90db83ee06",
          "md5": "29ee89461a22c381ac2b748c2f266d17"
        }
      ]
    }
  ]
}
