{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-data-elasticsearch",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-commons",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-elasticsearch",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-elasticsearch",
          "version": {
            "requires": "6.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-data-elasticsearch-4.0.5.jar",
          "url": "spring-boot-data-elasticsearch-4.0.5.jar",
          "size": 22668,
          "sha512": "44be60b9444c6713ded79db79d0dd05aad173631e57548a4defc3ab894ebb16f4acede4fe5dd91a940f221dae9be48da0042cf65f50d6cc574472a62413a3c99",
          "sha256": "cf5e2d81f1abba30c33fca9ffc727778de42f1cf69a17187aa0dc28d1add0a40",
          "sha1": "631d9288f727baff3ceb09abaff7a73fea560876",
          "md5": "c426846eb3c681e55c97068566b8bf2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-data-commons",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-elasticsearch",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-elasticsearch",
          "version": {
            "requires": "6.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-data-elasticsearch-4.0.5.jar",
          "url": "spring-boot-data-elasticsearch-4.0.5.jar",
          "size": 22668,
          "sha512": "44be60b9444c6713ded79db79d0dd05aad173631e57548a4defc3ab894ebb16f4acede4fe5dd91a940f221dae9be48da0042cf65f50d6cc574472a62413a3c99",
          "sha256": "cf5e2d81f1abba30c33fca9ffc727778de42f1cf69a17187aa0dc28d1add0a40",
          "sha1": "631d9288f727baff3ceb09abaff7a73fea560876",
          "md5": "c426846eb3c681e55c97068566b8bf2d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-data-elasticsearch-4.0.5-javadoc.jar",
          "url": "spring-boot-data-elasticsearch-4.0.5-javadoc.jar",
          "size": 127855,
          "sha512": "8dc31fe6e9caa15adad4834e6c6eadd2c1bc80c94cb986ed9330cd62aa3820c5f177f19115f70c9de72e9709d4bd6ebbb0149eaa874e135703f66716eb1715cf",
          "sha256": "043bacbfd3728dd824dca322f74a6c972c86ffb9a0a1763d2e1a26d94abf02e8",
          "sha1": "6dded24df9198f896ab6b979ad19483706992386",
          "md5": "3c1c74241aca691792f59b8ed666913c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-data-elasticsearch-4.0.5-sources.jar",
          "url": "spring-boot-data-elasticsearch-4.0.5-sources.jar",
          "size": 18508,
          "sha512": "e1178be716cb0f15a02c75c9d1c7eda2aa11d883a629b16c0caa4146018a64d92d3ca5e93e96f6c77793d579fa20d669da0bf2bc829b24b86d5ecd2440d12624",
          "sha256": "29d7b85b1b7cc3be477a872790593527df6eeeba5fe41e288a56304c56d92751",
          "sha1": "f8782e718f454aebc92b0a80f8358946012fd84d",
          "md5": "d1f0c9431abf0780fcfe7944a4d0ad44"
        }
      ]
    }
  ]
}
