{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-mongodb",
    "version": "4.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-mongodb-4.0.5.jar",
          "url": "spring-boot-mongodb-4.0.5.jar",
          "size": 51980,
          "sha512": "e277a39bb94eca6f78a5523ba80991b663d280a49c16ff467ad556d2c35d3d13b9b08dd63ec71fff49fb7b4164e413ed252dd9077aadd956259013e9374529d2",
          "sha256": "3233be6960ada0a25c2e9f29f9dee13c323dddee3ecdd9210d79b8c830b8e3e8",
          "sha1": "d532309eb5f6a80fc9053950be5e809de53e908c",
          "md5": "278ab6f192b5129e3c0cdb82a5552aab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-mongodb-4.0.5.jar",
          "url": "spring-boot-mongodb-4.0.5.jar",
          "size": 51980,
          "sha512": "e277a39bb94eca6f78a5523ba80991b663d280a49c16ff467ad556d2c35d3d13b9b08dd63ec71fff49fb7b4164e413ed252dd9077aadd956259013e9374529d2",
          "sha256": "3233be6960ada0a25c2e9f29f9dee13c323dddee3ecdd9210d79b8c830b8e3e8",
          "sha1": "d532309eb5f6a80fc9053950be5e809de53e908c",
          "md5": "278ab6f192b5129e3c0cdb82a5552aab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-mongodb-4.0.5-javadoc.jar",
          "url": "spring-boot-mongodb-4.0.5-javadoc.jar",
          "size": 172493,
          "sha512": "12bb7a2142056f56d9d252b14d9a82463a3c05469e19afda3d8c3cb8cbf262220d4d5730f97925a6b42f58a43551a5223334973d3d6a149682fdced1b6f631bf",
          "sha256": "4ca7b7172da0dcd5361f05784131967eec6398a830ece65e10f3c9f415532799",
          "sha1": "60bf840f81a8a19e3f08706931426b8ff8a4200c",
          "md5": "ee752a55c147765a1c3e51865c36b5e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-mongodb-4.0.5-sources.jar",
          "url": "spring-boot-mongodb-4.0.5-sources.jar",
          "size": 37776,
          "sha512": "2e524a51c9337d4ec250d881212d38503cbf98d82bcac8d0d87b220a9dd5ac336f66673cddd89b0f5fc51d7be92d4664a7db71bdb3a20073633bd2c886223452",
          "sha256": "6eaa3b86f108d61dba6da57a07f644323394f3b7da4f37df9bac218b8e85d03a",
          "sha1": "3e7a358b5ee5ce91e6a2953e58398353040ceb06",
          "md5": "71f36f4745d8dbc13b52aed63cacd6cd"
        }
      ]
    }
  ]
}
